# Generated by Django 5.2.5 on 2025-08-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='static_data',
        ),
        migrations.AlterField(
            model_name='datasource',
            name='data_source_type',
            field=models.CharField(choices=[('REST_API', 'REST API (Web Service)')], default='REST_API', help_text='How your app will get the data', max_length=20, verbose_name='Data Source Type'),
        ),
    ]
