# Generated by Django 5.2.5 on 2025-08-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_datasource_static_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='use_dynamic_base_url',
            field=models.BooleanField(default=False, help_text="If enabled, the base URL can be configured from the app's Configuration screen", verbose_name='Use Dynamic Base URL'),
        ),
        migrations.AlterField(
            model_name='widgetproperty',
            name='property_type',
            field=models.CharField(choices=[('string', 'Text'), ('integer', 'Number (Whole)'), ('decimal', 'Number (Decimal)'), ('boolean', 'True/False'), ('color', 'Color'), ('icon', 'Icon'), ('alignment', 'Alignment'), ('action_reference', 'Action (What Happens)'), ('data_source_field_reference', 'Data Field'), ('screen_reference', 'Screen Navigation'), ('asset_reference', 'Image/File'), ('url', 'Web Address'), ('json', 'Complex Data'), ('file_upload', 'File Upload'), ('date_picker', 'Date Picker'), ('time_picker', 'Time Picker'), ('map_location', 'Map Location'), ('rich_text', 'Rich Text Editor')], help_text='What type of value does this property need?', max_length=30, verbose_name='Property Type'),
        ),
    ]
